module.exports = {
  en: {
    translation: {
      home: {
        threekingdoms: "THREE KINGDOMS NFT",
        copyright: "Copyright 2022 three kingdoms club",
        comingsoon: "Coming Soon",
        bigGuysGather: "big guys gather",
        itsAllYou: "It's all you haven't heard of",
        roadmap: "Roadmap",
        team: "Team",
        general: "General",
        battle: "Battle",
        home: "Home",
      },
      roadmap: {
        p1_1: "Phase 1",
        p1_2: "Design of 4000 NFTs surrounding the classic characters of the Romance of the Three Kingdoms. (ERC721)",
        p1_3: "The NFT will be based on 60~80 classic Three Kingdoms characters, representative of the four forces of Wei, Shu Wu, and independent heroes. Artists will design based on the background stories of the Three Kingdoms and other characteristics of the characters, several unique Three Kingdoms character cards are randomly generated throughout the program.",
        p1_4: "Based on discord and mainstream social platforms for operation and management, we create a platform with the culture of the Three Kingdoms as the foundation and the goal of sharing Chinese culture to everyone around the world. Through high-quality art and our way of operating the community, members in WEB3.0 who are unfamiliar with Chinese culture can learn about the Three Kingdoms 'stories and spark interest. Building Chinese alpha channels. Regularly hold NFT community educational activities to create our own Chinese/Asian alpha community.",
        p1_5: "The official website is built, and the designed NFTs of the Three Kingdoms card characters will be sold.",
        p1_6: "Before all our NFTs can be seen, combo of the Three Kingdoms' characters card will be announced.",
        p1_7: "公布如桃园三结义（刘备、关羽、张飞），四大都督（周瑜、鲁肃、吕蒙、陆逊），五子良将（张辽 乐进 于禁 张郃 徐晃）等三国卡人物combo，满足条件持有者认证后可在第二阶段获得空投的土地。",
        p1_8: "Establish an open community account, and transfer some of the proceeds and royalties from the first phase to the subsequent development of the project.",
        p2_1: "Phase2",
        p2_2: "According to the territory of the Three Kingdoms period, the Three Kingdoms Land NFT will be issued. (ERC1155 or ERC721)",
        p2_3: "Compete against the Three Kingdoms land NFT, and release airdrops to the first group of people who meet the cobmo conditions of the Three Kingdoms.",
        p2_4: "Based on the land-staking system, land-staking participation and collaborating with other communities' whitelist spots, Three Kingdoms character card NFT, blue chip/hyped NFTs(purchased from an account which we'll let our community know), etc.",
        p2_5: "Based on the community of the Three Kingdoms NFT and the land NFT forces, the official website will establish a real-time update of the color for each factor, and officially open the era of secret battles amongst the members.",
        p2_6: "The propulsive country and echelon rank system is launched, and promotes the historical fronts of provinces and other places and counties to gain appeal, appear in the spheres of influence of various regions, and have different stages in each county government and other regions, and win rewards for each faction.",
        p2_7: "Profits from our second stage will be transferred to our public wallet address for further development.",
        p3_1: "Phase 3",
        p3_2: "Release profile-pic like NFTs of the characters of the Three Kingdoms. Each work in this series is an original art, not a program synthesis. (ERC721/Wrapped NFT pending)",
        p3_3: "The NFT art of the Three Kingdoms characters in the PFP category will be sold, and airdrops will be issued to the holders who meet the conditions in the first and second stages.",
        p3_4: "Through community collaboration and functional development, NFTs in the first and second stages will be continuously empowered, and the ecology of the Three Kingdoms NFT Metaverse will be improved.",
        p3_5: "War System and Community Self-Government System. (pending)",
        p3_6: "Part of the total project revenue pool will be used to support more high-quality Chinese cultural projects in the future.",
      },
    },
  },
  zh: {
    translation: {
      home: {
        threekingdoms: "THREE KINGDOMS NFT",
        copyright: "Copyright 2022 three kingdoms club",
        comingsoon: "敬请期待",
        bigGuysGather: "大男人聚集",
        itsAllYou: "你没听说过",
        roadmap: "路线",
        team: "组员",
        general: "常规",
        battle: "掰头",
        home: "主页",
      },
      roadmap: {
        p1_1: "初出茅庐",
        p1_2: "围绕三国经典人物发行4000-6000个NFT。（ERC721)",
        p1_3: "NFT将以魏蜀吴群四个势力中具有代表性的60~80个经典三国人物为原型， 艺术家会根据三国的背景故事进行设计，每名三国人物都会根据性别、文武、服饰、头饰、背景等特性，通过程序随机的生成出若干个独一无二的三国人物收藏卡。",
        p1_4: "基于discord和主流的社交平台进行运营和管理，打造一个以三国文化为底蕴，以对外输出中华文化为目标的平台，通过优质作品和运营方式让WEB3.0中不熟悉中华文化的人们能对三国故事和题材燃起兴趣。构建中文alpha频道。定期举办NFT社区教育活动，打造属于我们自己的中文/亚裔alpha社区。",
        p1_5: "官方网站搭建，对设计完成的三国卡人物NFT进行发售。",
        p1_6: "开图前公布三国卡人物combo。",
        p1_7: "公布如桃园三结义（刘备、关羽、张飞），四大都督（周瑜、鲁肃、吕蒙、陆逊），五子良将（张辽 乐进 于禁 张郃 徐晃）等三国卡人物combo，满足条件持有者认证后可在第二阶段获得空投的土地。",
        p1_8: "建立公开社区账户，转入第一阶段部分收益及版税收益用于项目后续发展。",
        p2_1: "群雄割据",
        p2_2: "根据三国时期的版图，发行三国土地NFT。（ERC1155 或 ERC721）",
        p2_3: "对三国土地NFT进行发售，向第一阶段满足三国人物卡cobmo条件者发放空投。",
        p2_4: "上线土地质押系统，质押土地参与抽取与其他社区合作的白名单、三国人物卡NFT、市场火热NFT（社区公开账户购买）等福利。",
        p2_5: "社区基于三国人物卡NFT和土地NFT建立魏蜀吴群四大势力，官方网站认证土地后实时更新各势力颜色分布，正式开启明争暗斗、尔虞我诈的群雄割据时代。",
        p2_6: "各个势力等级系统上线，出现主公、刺史、郡守等角色，带领号召所属势力逐鹿天下，通过内政外交等手段占领土地，阶段性成功占领各县、州、国等地区将会获得不同的奖励。",
        p2_7: "向社区公开账户转入第二阶段部分收益用于项目后续发展。",
        p3_1: "一齐天下",
        p3_2: "通过第一阶段和第二阶段的运营，我们会在第三阶段推出一个交互艺术pfp NFT。该作品会基于第一第二阶段进行快照，通过玩家和nft作品的协作，通过技术手段生成独一无二的PFP作品。例如，玩家持有关羽，在第三阶段mint期间，有概率在pfp上面出现青龙偃月刀的武器。（ERC721/Wrapped NFT待定）",
        p3_3: "对PFP头像类的三国人物NFT作品进行发售。",
        p3_4: "对第一第二阶段的NFT通过社区合作及功能开发实现持续赋能，完善三国NFT元宇宙的生态，例如，sandbox，webb等元宇宙概念生态。",
        p3_5: "通过元宇宙生态完善战争系统与社区自治系统。（待定）",
        p3_6: "项目总收益池部分份额用于扶持未来更多优质的中华文化项目。",
      },
    },
  },
};
